# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '40 10 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale as it has no recent activity. Submit a comment or mark this issue as resolved otherwise it will be closed.'
        stale-pr-message: 'This pull request has been marked as stale as it has no recent activity. Submit a comment or mark this request as resolved otherwise it will be closed and not merged.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        close-issue-message: 'This issue has been closed due to inactivity.'
        close-pr-message: 'This pull request has been closed due to inactivity.'
        days-before-stale: 14
